server:
  port: 8084
spring:
  application:
    name: searchservice
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.93.132:8848
    openfeign:
      client:
        config:
          default: # default全局的配置
            loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
      httpclient:
        enabled: true #开启feign对HttpClient的支持
        max-connections: 200 # 最大的连接数
        max-connections-per-route: 50 # 每个路径的最大连接数
  rabbitmq:
    host: 192.168.93.132
    port: 5672
    virtual-host: /
    username: jensen
    password: 123456
logging:
  level:
    cn.itcast.feign.client: debug
  pattern:
    dateformat: HH:mm:ss:SSS
elasticsearch:
  host: 192.168.93.132
  port: 9200